# @package _global_

exp_group: im21k
exp_name: bert-bce

model:
  backbone: ImageNet21k-ViT-B
  classifier: bert

loss:
  name: BCE

wandb: True
epochs: 20
save_freq: ${scheduler.T_0}
val_freq: ${scheduler.T_0}