# @package _global_

exp_group: im21k
exp_name: bert-sign

model:
  backbone: ImageNet21k-ViT-B
  classifier: bert

loss:
  name: Sign

wandb: True
epochs: 10
save_freq: ${scheduler.T_0}
val_freq: ${scheduler.T_0}