# @package _global_

exp_group: im21k
exp_name: rand-linear-bce

model:
  backbone: ImageNet21k-ViT-B
  classifier: rand-linear
  log_scale: 0.0
  log_scale_trainable: False

loss:
  name: BCE

wandb: True
epochs: 20
save_freq: ${scheduler.T_0}
val_freq: ${scheduler.T_0}