# @package _global_

exp_group: clip
exp_name: clip-wbce

optim:
  base_lr: 1.5e-5

model:
  classifier: clip

loss:
  name: WBCE

wandb: True
epochs: 40
save_freq: ${scheduler.T_0}
val_freq: ${scheduler.T_0}