# @package _global_

exp_group: clip
exp_name: clip-sign

optim:
  base_lr: 1.5e-5

model:
  classifier: clip

loss:
  name: Sign

wandb: True
epochs: 10
save_freq: ${scheduler.T_0}
val_freq: ${scheduler.T_0}