# @package _global_

exp_group: clip
exp_name: rand-bce

optim:
  base_lr: 1.5e-5

model:
  classifier: rand

loss:
  name: BCE

wandb: True
epochs: 40
save_freq: ${scheduler.T_0}
val_freq: ${scheduler.T_0}